#!/bin/bash
cd
m=0
while (("${m}" <= "685210"))
do
    h=$(haqqd status |jq .SyncInfo.latest_block_height)
    # убираем ковычку
    m=$(sed -e 's/^"//' -e 's/"$//' <<<"$h")
    echo "tek vysota" ${m}
    sleep 1
done

echo gotov
