#!/bin/bash
echo "-----------------------------------------------------------------------------"

cd $HOME/haqq
git pull
git checkout v1.3.1
make build
`$HOME/haqq/build/haqqd version --long | grep -e version -e commit`

m=0
while (("${m}" < "2229900"))
do
    m=$(haqqd status |jq .SyncInfo.latest_block_height | xargs)
    dig=`echo "digid" | awk '/(^[0-9]{2,6}$)/'${m}`
    if [ "$dig" = "digid" ];then
      echo "current height" ${m}
    else
      echo "net otveta"
      m=0
    fi
    sleep 1
done
sudo systemctl stop haqqd
mv $HOME/haqq/build/haqqd $(which haqqd)
echo "версия бинарника: "
echo `haqqd version`
sudo systemctl restart haqqd && journalctl -u haqqd -f -o cat
