#!/bin/bash
echo "-----------------------------------------------------------------------------"

cd $HOME/sao-consensus
git pull
git checkout v0.1.5
make build
for((;;)); do
    height=$(saod status |& jq -r ."SyncInfo"."latest_block_height")
    if ((height== 4007000)); then
      systemctl stop saod
      mv $HOME/sao-consensus/build/saod $(which saod)
      sudo systemctl restart saod
      echo "restart"
      break
    else
      echo $height
    fi
    sleep 1
done
journalctl -u saod -f -o cat
