#!/bin/bash
echo "-----------------------------------------------------------------------------"

nodedir="$HOME/story"

cd $nodedir
sleep 1

for((;;)); do
    height=$(curl -s http://167.235.39.5:26657/status | jq -r .result.sync_info.latest_block_height)
    if ((height == 1069000)); then
      systemctl stop "$binarnik"
      mv /root/story/geth-linux-amd64-0.9.3-b224fdf/geth /usr/local/bin/  
      sudo systemctl restart "$storyservice"
      echo "restart"
      break
    else
      echo $height
    fi
    sleep 1
done
journalctl -u "$storyservice" -f -o cat
